create table if not exists public.shlokas (
  id bigint generated by default as identity primary key,
  category text not null default 'Everyone',
  title text not null,
  sanskrit text not null,
  transliteration text,
  english text not null,
  marathi text not null,
  hindi text not null,
  meaning text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.shlokas enable row level security;

create policy "public can read shlokas"
on public.shlokas for select to anon, authenticated using (true);

create policy "admin can insert shlokas"
on public.shlokas for insert to authenticated with check (true);

create policy "admin can update shlokas"
on public.shlokas for update to authenticated using (true) with check (true);

create policy "admin can delete shlokas"
on public.shlokas for delete to authenticated using (true);

insert into public.shlokas (
  id, category, title, sanskrit, transliteration, english, marathi, hindi, meaning, message
) values
  (1, 'For Mother', 'For Mother', 'स्वधर्मे निधनं श्रेयः परधर्मो भयावहः।', 'Swadharme nidhanam shreyah paradharmo bhayavahah.', 'It is better to perform one''s own duty, even imperfectly, than to perform another''s duty perfectly.', 'स्वतःचे कर्तव्य अपूर्णपणे केले तरी ते दुसऱ्याचे कर्तव्य उत्तम प्रकारे करण्यापेक्षा श्रेष्ठ आहे.', 'अपने कर्तव्य को अपूर्ण रूप से करना भी दूसरे के कर्तव्य को पूर्णता से करने से श्रेष्ठ है।', 'Honour your own path and responsibilities instead of comparing your journey with someone else''s.', 'आईसाठी: तुमची काळजी, ताकद आणि जबाबदाऱ्या अनोख्या आहेत. प्रेमाने आणि प्रामाणिकपणे केलेले प्रत्येक कार्य मौल्यवान आहे.'),
  (2, 'For Father', 'For Father', 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।', 'Karmany evadhikaraste ma phaleshu kadachana.', 'You have a right to your actions, but not to the fruits of those actions.', 'तुला तुझ्या कर्मावर अधिकार आहे; त्याच्या फळावर नाही.', 'तुम्हारा अधिकार केवल कर्म करने में है, उसके फल पर नहीं।', 'Focus on sincere effort and do not let worry about results control you.', 'वडिलांसाठी: कुटुंबासाठी केलेला प्रत्येक प्रामाणिक प्रयत्न महत्त्वाचा आहे.'),
  (3, 'For Students', 'For Students', 'श्रद्धावान् लभते ज्ञानं तत्परः संयतेन्द्रियः।', 'Shraddhavan labhate jnanam tatparah samyatendriyah.', 'One who has faith, dedication and control over the senses gains knowledge.', 'श्रद्धा, समर्पण आणि इंद्रियसंयम असणाऱ्या व्यक्तीला ज्ञान प्राप्त होते.', 'जिसमें श्रद्धा, समर्पण और इन्द्रियों पर संयम है, उसे ज्ञान प्राप्त होता है।', 'Consistency, attention and discipline turn learning into wisdom.', 'विद्यार्थ्यांसाठी: जिज्ञासा शिकण्याची सुरुवात आहे; पण शिस्त आणि सातत्य ज्ञानाला कौशल्यात बदलतात.'),
  (4, 'For Professionals', 'For Professionals', 'योगः कर्मसु कौशलम्।', 'Yogah karmasu kaushalam.', 'Yoga is excellence and skillfulness in action.', 'कर्मातील कौशल्य आणि उत्कृष्टताच योग आहे.', 'कर्म में कुशलता ही योग है।', 'Do your work with awareness, competence and integrity.', 'कामात गुणवत्ता, कौशल्य, प्रामाणिकपणा आणि जबाबदारी ठेवणे हीच खरी साधना.'),
  (5, 'For Couples', 'For Couples', 'सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।', 'Sukha-duhkhe same kritva labhalabhau jayajayau.', 'Treat happiness and sorrow, gain and loss, victory and defeat with equanimity.', 'सुख-दुःख, लाभ-हानी, जय-पराजय यांना समभावाने स्वीकारावे.', 'सुख-दुःख, लाभ-हानि और जय-पराजय को समान भाव से स्वीकार करो।', 'A strong relationship needs balance through changing circumstances.', 'नात्यातील चांगले आणि कठीण दिवस दोन्ही आदर, समजूतदारपणा आणि स्थिरतेने सामोरे जा.'),
  (6, 'For Youth', 'For Youth', 'मन एव मनुष्याणां कारणं बन्धमोक्षयोः।', 'Mana eva manushyanam karanam bandhamokshayoh.', 'The mind alone can be the cause of bondage as well as liberation.', 'मनुष्याच्या बंधनाचे आणि मुक्तीचे कारण मनच आहे.', 'मनुष्य के बंधन और मुक्ति का कारण मन ही है।', 'Your mindset can become your greatest obstacle or your greatest strength.', 'तरुणांसाठी: मनाला दिशा दिली तर ते अडथळा न राहता तुमची सर्वात मोठी ताकद बनते.'),
  (7, 'For People in Struggle', 'For People in Struggle', 'उद्धरेदात्मनाऽऽत्मानं नात्मानमवसादयेत्।', 'Uddhared atmanatmanam natmanam avasadayet.', 'Let a person lift oneself by oneself; do not let oneself fall.', 'स्वतःने स्वतःला उन्नत करावे; स्वतःला खचू देऊ नये.', 'मनुष्य को स्वयं अपने द्वारा अपना उद्धार करना चाहिए, स्वयं को नीचे नहीं गिराना चाहिए।', 'When life becomes difficult, begin by strengthening yourself from within.', 'अडचणीच्या वेळी हार मानू नका. मदत घ्या, पण पुढचे सकारात्मक पाऊल स्वतः उचलण्याची ताकद जपा.'),
  (8, 'For Everyone', 'For Everyone', 'समत्वं योग उच्यते।', 'Samatvam yoga uchyate.', 'Equanimity is called Yoga.', 'समत्वालाच योग असे म्हटले आहे.', 'समत्व को ही योग कहा जाता है।', 'Stay balanced in success and failure, praise and criticism.', 'यश-अपयश, कौतुक-टीका यामध्ये मनाचा समतोल राखणे ही खरी शक्ती आहे.'),
  (9, 'Control Anger', 'Control Anger', 'क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः।', 'Krodhad bhavati sammohah sammohat smritivibhramah.', 'From anger comes delusion; from delusion, confusion of memory and judgment.', 'क्रोधामुळे भ्रम निर्माण होतो आणि भ्रमामुळे स्मरणशक्ती व विवेक गोंधळतो.', 'क्रोध से मोह उत्पन्न होता है और मोह से स्मृति व विवेक भ्रमित हो जाते हैं।', 'Uncontrolled anger can cloud judgment and lead to destructive decisions.', 'रागाच्या क्षणी थांबा, श्वास घ्या आणि मग उत्तर द्या. काही क्षणांची जाणीव मोठी चूक टाळू शकते.'),
  (10, 'Success & Failure', 'Success & Failure', 'सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते।', 'Siddhy-asiddhyoh samo bhutva samatvam yoga uchyate.', 'Remain even-minded in success and failure; such balance is called Yoga.', 'यश-अपयशात समभाव ठेवणे हाच योग आहे.', 'सफलता और असफलता में समभाव रखना ही योग है।', 'Give your best without allowing the result to define your worth.', 'यशात अहंकार नको आणि अपयशात निराशा नको. दोन्ही अनुभव प्रवासाचा भाग आहेत.')
on conflict (id) do nothing;
