create table if not exists public.shlokas (
  id bigint generated by default as identity primary key,
  problem text not null,
  solution text not null,
  title text not null,
  chapter integer not null,
  verse integer not null,
  sanskrit text not null,
  transliteration text,
  english text not null,
  marathi text not null,
  hindi text not null,
  meaning text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.shlokas enable row level security;

drop policy if exists "public can read shlokas" on public.shlokas;
drop policy if exists "admin can insert shlokas" on public.shlokas;
drop policy if exists "admin can update shlokas" on public.shlokas;
drop policy if exists "admin can delete shlokas" on public.shlokas;
create policy "public can read shlokas" on public.shlokas for select to anon, authenticated using (true);
create policy "admin can insert shlokas" on public.shlokas for insert to authenticated with check (true);
create policy "admin can update shlokas" on public.shlokas for update to authenticated using (true) with check (true);
create policy "admin can delete shlokas" on public.shlokas for delete to authenticated using (true);

create unique index if not exists shlokas_chapter_verse_key on public.shlokas (chapter, verse);

-- Remove only the six original demo records. Unrelated admin/user data is preserved.
delete from public.shlokas
where (problem, solution) in (
  ('Stress', 'Patience'), ('Anger', 'Self-Control'), ('Fear', 'Courage'),
  ('Comparison', 'Self-Belief'), ('Failure', 'Learning'), ('Distraction', 'Focus')
);

-- Re-running this migration updates the eight canonical verses without duplicates.
insert into public.shlokas (
  id, problem, solution, title, chapter, verse, sanskrit, transliteration,
  english, marathi, hindi, meaning, message
) values
(1, 'कर्म', 'निष्काम कर्म', 'कर्म पर ध्यान — फल की चिंता से मुक्ति', 2, 47,
 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥',
 'karmaṇy evādhikāras te mā phaleṣu kadācana |
mā karma-phala-hetur bhūr mā te saṅgo ''stv akarmaṇi ||',
 'You have the right to perform your actions, but not to the results of those actions. Do not make the result the sole motive of your action, nor become attached to inaction.',
 'तुला कर्म करण्याचा अधिकार आहे; त्याच्या फळावर तुझा अधिकार नाही. कर्माच्या फळालाच आपल्या कृतीचे एकमेव उद्दिष्ट मानू नकोस आणि निष्क्रियतेशीही आसक्त होऊ नकोस.',
 'तुम्हारा अधिकार केवल कर्म करने में है, उसके फल में नहीं। कर्म के फल को ही अपने कर्म का एकमात्र उद्देश्य मत बनाओ और अकर्मण्यता में भी आसक्त मत हो।',
 'Do your work sincerely and give your best effort without allowing the result to control your peace of mind.',
 'Focus on what you can do today. Let the result come in its own time.'),
(2, 'ज्ञान', 'ज्ञान की शक्ति', 'ज्ञान — जीवन को प्रकाशित करने वाली शक्ति', 4, 38,
 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते ।
तत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति ॥',
 'na hi jñānena sadṛśaṃ pavitram iha vidyate |
tat svayaṃ yoga-saṃsiddhaḥ kālenātmani vindati ||',
 'There is nothing in this world as purifying as knowledge. One who becomes perfected through Yoga realizes that knowledge within oneself in due course.',
 'या जगात ज्ञानासारखे पवित्र करणारे दुसरे काहीही नाही. योगाने सिद्ध झालेला मनुष्य योग्य वेळी ते ज्ञान आपल्या अंतःकरणात अनुभवतो.',
 'इस संसार में ज्ञान के समान पवित्र करने वाला कुछ भी नहीं है। योग में सिद्ध हुआ व्यक्ति समय के साथ उस ज्ञान को अपने भीतर अनुभव करता है।',
 'True knowledge does more than give information; it transforms the way we understand ourselves and life.',
 'Keep learning. Knowledge turns confusion into clarity.'),
(3, 'धैर्य', 'स्थिरता', 'धैर्य — कठीण काळात मनाची स्थिरता', 18, 33,
 'धृत्या यया धारयते मनःप्राणेन्द्रियक्रियाः ।
योगेनाव्यभिचारिण्या धृतिः सा पार्थ सात्त्विकी ॥',
 'dhṛtyā yayā dhārayate manaḥ-prāṇendriya-kriyāḥ |
yogenāvyabhicāriṇyā dhṛtiḥ sā pārtha sāttvikī ||',
 'O Arjuna, that firmness by which one steadily sustains the activities of the mind, vital forces, and senses through unwavering practice is called firmness born of goodness.',
 'हे पार्था, ज्या अढळ धैर्याने योगाच्या मार्गावर मन, प्राण आणि इंद्रियांच्या क्रियांना स्थिर ठेवले जाते, त्या धैर्याला सात्त्विक धृती म्हणतात.',
 'हे पार्थ, जिस अटल धैर्य के द्वारा मन, प्राण और इन्द्रियों की क्रियाओं को निरंतर योग में स्थिर रखा जाता है, उस धैर्य को सात्त्विक धृति कहा जाता है।',
 'Patience is not simply waiting. It is the inner strength to remain steady while continuing the right effort.',
 'Stay steady when life becomes difficult. Strength grows through consistency.'),
(4, 'संयम', 'आत्मनियंत्रण', 'संयम — स्वयं पर नियंत्रण', 2, 58,
 'यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः ।
इन्द्रियाणीन्द्रियार्थेभ्यस्तस्य प्रज्ञा प्रतिष्ठिता ॥',
 'yadā saṃharate cāyaṃ kūrmo ''ṅgānīva sarvaśaḥ |
indriyāṇīndriyārthebhyas tasya prajñā pratiṣṭhitā ||',
 'When a person withdraws the senses from their objects, just as a tortoise withdraws its limbs, their wisdom becomes firmly established.',
 'जसा कासव आपल्या अवयवांना सर्व बाजूंनी आत ओढून घेतो, त्याप्रमाणे जो मनुष्य आपल्या इंद्रियांना त्यांच्या विषयांपासून दूर ठेवतो, त्याची बुद्धी स्थिर होते.',
 'जैसे कछुआ अपने अंगों को चारों ओर से समेट लेता है, वैसे ही जो व्यक्ति अपनी इन्द्रियों को उनके विषयों से हटा लेता है, उसकी बुद्धि स्थिर हो जाती है।',
 'Self-control means knowing when to step back from distractions, impulses, and temptations.',
 'Real control is not controlling the world; it is learning to control yourself.'),
(5, 'दृढ़ता', 'एकाग्र संकल्प', 'दृढ़ता — एकाग्र मन आणि ठाम संकल्प', 2, 41,
 'व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन ।
बहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम् ॥',
 'vyavasāyātmikā buddhir ekeha kuru-nandana |
bahu-śākhā hy anantāś ca buddhayo ''vyavasāyinām ||',
 'O joy of the Kurus, the resolute mind is one-pointed, whereas the thoughts of the irresolute are many-branched and endless.',
 'हे कुरुनंदना, दृढनिश्चयी मनाची बुद्धी एकाग्र आणि एकमुखी असते; पण ज्यांचा निश्चय दृढ नसतो, त्यांच्या बुद्धीचे विचार अनेक दिशांना विखुरलेले असतात.',
 'हे कुरुनन्दन, दृढ़ निश्चय वाले व्यक्ति की बुद्धि एकाग्र होती है, जबकि अस्थिर और अनिश्चित मन वाले लोगों के विचार अनेक दिशाओं में भटकते रहते हैं।',
 'When your purpose is clear, your mind becomes focused instead of constantly moving in different directions.',
 'A clear goal gives your energy a direction.'),
(6, 'भक्ति', 'ईश्वराशी जोडलेले मन', 'भक्ति — मन आणि बुद्धी परमेश्वराशी जोडणे', 12, 8,
 'मय्येव मन आधत्स्व मयि बुद्धिं निवेशय ।
निवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः ॥',
 'mayy eva mana ādhatsva mayi buddhiṃ niveśaya |
nivasiṣyasi mayy eva ata ūrdhvaṃ na saṃśayaḥ ||',
 'Fix your mind on Me alone and place your intellect in Me. Then you will dwell in Me; there is no doubt about it.',
 'तुझे मन माझ्यात स्थिर कर आणि तुझी बुद्धी माझ्यात अर्पण कर. त्यानंतर तू माझ्यातच स्थित होशील; यात काहीही संशय नाही.',
 'अपने मन को मुझमें स्थिर करो और अपनी बुद्धि को मुझमें लगाओ। तब तुम मुझमें ही स्थित रहोगे; इसमें कोई संदेह नहीं है।',
 'Bhakti means directing the mind and intellect toward the Divine with trust, remembrance, and surrender.',
 'When the mind has something higher to hold on to, life becomes calmer and more meaningful.'),
(7, 'समरसता', 'समत्व', 'समरसता — सुख-दुःखात समभाव', 2, 48,
 'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय ।
सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ॥',
 'yogasthaḥ kuru karmāṇi saṅgaṃ tyaktvā dhanañjaya |
siddhy-asiddhyoḥ samo bhūtvā samatvaṃ yoga ucyate ||',
 'Established in Yoga, perform your actions without attachment. Remain even-minded in success and failure; this evenness of mind is called Yoga.',
 'हे धनंजया, योगात स्थिर राहून आसक्ती सोडून कर्म कर. यश आणि अपयश दोन्हीमध्ये समभाव ठेव; या समत्वालाच योग म्हटले आहे.',
 'हे धनंजय, योग में स्थित होकर आसक्ति छोड़कर कर्म करो। सफलता और असफलता में समान भाव रखो; इसी समत्व को योग कहा गया है।',
 'Balance does not mean having no emotions. It means not allowing success or failure to control your inner state.',
 'Stay humble in success and strong in failure.'),
(8, 'सत्य', 'सत्यप्रिय वाणी', 'सत्य — सत्य आणि करुणामय वाणी', 17, 15,
 'अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत् ।
स्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते ॥',
 'anudvega-karaṃ vākyaṃ satyaṃ priya-hitaṃ ca yat |
svādhyāyābhyasanaṃ caiva vāṅ-mayaṃ tapa ucyate ||',
 'Speech that does not cause distress, that is truthful, pleasant, and beneficial, together with the disciplined study of sacred knowledge, is called austerity of speech.',
 'ज्या वाणीमुळे कोणाला उद्वेग होत नाही, जी सत्य, प्रिय आणि हितकारक आहे, तसेच स्वाध्यायाचा अभ्यास — याला वाणीचे तप म्हटले आहे.',
 'जो वचन किसी को उद्विग्न न करे, जो सत्य, प्रिय और हितकारी हो, तथा स्वाध्याय का अभ्यास — इसे वाणी का तप कहा गया है।',
 'Speaking the truth is important, but truth should also be expressed with kindness and concern for others.',
 'Speak the truth, but let your words heal rather than hurt.')
on conflict (id) do update set
  problem = excluded.problem, solution = excluded.solution, title = excluded.title,
  chapter = excluded.chapter, verse = excluded.verse, sanskrit = excluded.sanskrit,
  transliteration = excluded.transliteration, english = excluded.english,
  marathi = excluded.marathi, hindi = excluded.hindi, meaning = excluded.meaning,
  message = excluded.message;

-- Keep the identity sequence ahead of the seeded IDs for later admin inserts.
select setval(pg_get_serial_sequence('public.shlokas', 'id'), greatest((select max(id) from public.shlokas), 1), true);
